// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.ephemq.remote.proto.server;

public interface CalculatePartitionsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meteor.protobuf.CalculatePartitionsRequest)
    com.google.protobuf.MessageOrBuilder {
}
