// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.ephemq.remote.proto.server;

public interface CancelSyncResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meteor.protobuf.CancelSyncResponse)
    com.google.protobuf.MessageOrBuilder {
}
