// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.ephemq.remote.proto.server;

public interface QueryClusterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meteor.protobuf.QueryClusterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.meteor.protobuf.ClusterInfo cluster_info = 1;</code>
   * @return Whether the clusterInfo field is set.
   */
  boolean hasClusterInfo();
  /**
   * <code>.meteor.protobuf.ClusterInfo cluster_info = 1;</code>
   * @return The clusterInfo.
   */
  org.ephemq.remote.proto.ClusterInfo getClusterInfo();
  /**
   * <code>.meteor.protobuf.ClusterInfo cluster_info = 1;</code>
   */
  org.ephemq.remote.proto.ClusterInfoOrBuilder getClusterInfoOrBuilder();
}
