// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sraft.proto

package org.shallow.remote.proto.elector;

import org.shallow.remote.proto.NodeMetadata;
import org.shallow.remote.proto.NodeMetadataOrBuilder;

public interface UnRegisterNodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shallow.protobuf.UnRegisterNodeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cluster = 1;</code>
   * @return The cluster.
   */
  java.lang.String getCluster();
  /**
   * <code>string cluster = 1;</code>
   * @return The bytes for cluster.
   */
  com.google.protobuf.ByteString
      getClusterBytes();

  /**
   * <code>.shallow.protobuf.NodeMetadata metadata = 2;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.shallow.protobuf.NodeMetadata metadata = 2;</code>
   * @return The metadata.
   */
  NodeMetadata getMetadata();
  /**
   * <code>.shallow.protobuf.NodeMetadata metadata = 2;</code>
   */
  NodeMetadataOrBuilder getMetadataOrBuilder();
}
