// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meteor.proto

package org.meteor.remote.proto;

public interface ClusterInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meteor.protobuf.ClusterInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.meteor.protobuf.ClusterMetadata cluster = 1;</code>
   * @return Whether the cluster field is set.
   */
  boolean hasCluster();
  /**
   * <code>.meteor.protobuf.ClusterMetadata cluster = 1;</code>
   * @return The cluster.
   */
  org.meteor.remote.proto.ClusterMetadata getCluster();
  /**
   * <code>.meteor.protobuf.ClusterMetadata cluster = 1;</code>
   */
  org.meteor.remote.proto.ClusterMetadataOrBuilder getClusterOrBuilder();

  /**
   * <code>map&lt;string, .meteor.protobuf.NodeMetadata&gt; nodes = 2;</code>
   */
  int getNodesCount();
  /**
   * <code>map&lt;string, .meteor.protobuf.NodeMetadata&gt; nodes = 2;</code>
   */
  boolean containsNodes(
      java.lang.String key);
  /**
   * Use {@link #getNodesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.meteor.remote.proto.NodeMetadata>
  getNodes();
  /**
   * <code>map&lt;string, .meteor.protobuf.NodeMetadata&gt; nodes = 2;</code>
   */
  java.util.Map<java.lang.String, org.meteor.remote.proto.NodeMetadata>
  getNodesMap();
  /**
   * <code>map&lt;string, .meteor.protobuf.NodeMetadata&gt; nodes = 2;</code>
   */

  /* nullable */
org.meteor.remote.proto.NodeMetadata getNodesOrDefault(
      java.lang.String key,
      /* nullable */
org.meteor.remote.proto.NodeMetadata defaultValue);
  /**
   * <code>map&lt;string, .meteor.protobuf.NodeMetadata&gt; nodes = 2;</code>
   */

  org.meteor.remote.proto.NodeMetadata getNodesOrThrow(
      java.lang.String key);
}
