// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meteor.proto

package org.meteor.remote.proto;

/**
 * Protobuf type {@code meteor.protobuf.MessageId}
 */
public final class MessageId extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:meteor.protobuf.MessageId)
        MessageIdOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use MessageId.newBuilder() to construct.
    private MessageId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private MessageId() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new MessageId();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return org.meteor.remote.proto.MessageMetadataProto.internal_static_meteor_protobuf_MessageId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return org.meteor.remote.proto.MessageMetadataProto.internal_static_meteor_protobuf_MessageId_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        org.meteor.remote.proto.MessageId.class, org.meteor.remote.proto.MessageId.Builder.class);
    }

    public static final int LEDGER_FIELD_NUMBER = 1;
    private int ledger_;

    /**
     * <code>int32 ledger = 1;</code>
     *
     * @return The ledger.
     */
    @java.lang.Override
    public int getLedger() {
        return ledger_;
    }

    public static final int EPOCH_FIELD_NUMBER = 2;
    private int epoch_;

    /**
     * <code>int32 epoch = 2;</code>
     *
     * @return The epoch.
     */
    @java.lang.Override
    public int getEpoch() {
        return epoch_;
    }

    public static final int INDEX_FIELD_NUMBER = 3;
    private int index_;

    /**
     * <code>int32 index = 3;</code>
     *
     * @return The index.
     */
    @java.lang.Override
    public int getIndex() {
        return index_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) {
            return true;
        }
        if (isInitialized == 0) {
            return false;
        }

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (ledger_ != 0) {
            output.writeInt32(1, ledger_);
        }
        if (epoch_ != 0) {
            output.writeInt32(2, epoch_);
        }
        if (index_ != 0) {
            output.writeInt32(3, index_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) {
            return size;
        }

        size = 0;
        if (ledger_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(1, ledger_);
        }
        if (epoch_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(2, epoch_);
        }
        if (index_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(3, index_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof org.meteor.remote.proto.MessageId)) {
            return super.equals(obj);
        }
        org.meteor.remote.proto.MessageId other = (org.meteor.remote.proto.MessageId) obj;

        if (getLedger()
                != other.getLedger()) {
            return false;
        }
        if (getEpoch()
                != other.getEpoch()) {
            return false;
        }
        if (getIndex()
                != other.getIndex()) {
            return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) {
            return false;
        }
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + LEDGER_FIELD_NUMBER;
        hash = (53 * hash) + getLedger();
        hash = (37 * hash) + EPOCH_FIELD_NUMBER;
        hash = (53 * hash) + getEpoch();
        hash = (37 * hash) + INDEX_FIELD_NUMBER;
        hash = (53 * hash) + getIndex();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static org.meteor.remote.proto.MessageId parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.meteor.remote.proto.MessageId parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.meteor.remote.proto.MessageId parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.meteor.remote.proto.MessageId parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.meteor.remote.proto.MessageId parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.meteor.remote.proto.MessageId parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.meteor.remote.proto.MessageId parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static org.meteor.remote.proto.MessageId parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.meteor.remote.proto.MessageId parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.meteor.remote.proto.MessageId parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.meteor.remote.proto.MessageId parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static org.meteor.remote.proto.MessageId parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(org.meteor.remote.proto.MessageId prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code meteor.protobuf.MessageId}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:meteor.protobuf.MessageId)
            org.meteor.remote.proto.MessageIdOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return org.meteor.remote.proto.MessageMetadataProto.internal_static_meteor_protobuf_MessageId_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return org.meteor.remote.proto.MessageMetadataProto.internal_static_meteor_protobuf_MessageId_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.meteor.remote.proto.MessageId.class, org.meteor.remote.proto.MessageId.Builder.class);
        }

        // Construct using org.meteor.remote.proto.MessageId.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);

        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            ledger_ = 0;

            epoch_ = 0;

            index_ = 0;

            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return org.meteor.remote.proto.MessageMetadataProto.internal_static_meteor_protobuf_MessageId_descriptor;
        }

        @java.lang.Override
        public org.meteor.remote.proto.MessageId getDefaultInstanceForType() {
            return org.meteor.remote.proto.MessageId.getDefaultInstance();
        }

        @java.lang.Override
        public org.meteor.remote.proto.MessageId build() {
            org.meteor.remote.proto.MessageId result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public org.meteor.remote.proto.MessageId buildPartial() {
            org.meteor.remote.proto.MessageId result = new org.meteor.remote.proto.MessageId(this);
            result.ledger_ = ledger_;
            result.epoch_ = epoch_;
            result.index_ = index_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof org.meteor.remote.proto.MessageId) {
                return mergeFrom((org.meteor.remote.proto.MessageId) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(org.meteor.remote.proto.MessageId other) {
            if (other == org.meteor.remote.proto.MessageId.getDefaultInstance()) {
                return this;
            }
            if (other.getLedger() != 0) {
                setLedger(other.getLedger());
            }
            if (other.getEpoch() != 0) {
                setEpoch(other.getEpoch());
            }
            if (other.getIndex() != 0) {
                setIndex(other.getIndex());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            ledger_ = input.readInt32();

                            break;
                        } // case 8
                        case 16: {
                            epoch_ = input.readInt32();

                            break;
                        } // case 16
                        case 24: {
                            index_ = input.readInt32();

                            break;
                        } // case 24
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int ledger_;

        /**
         * <code>int32 ledger = 1;</code>
         *
         * @return The ledger.
         */
        @java.lang.Override
        public int getLedger() {
            return ledger_;
        }

        /**
         * <code>int32 ledger = 1;</code>
         *
         * @param value The ledger to set.
         * @return This builder for chaining.
         */
        public Builder setLedger(int value) {

            ledger_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 ledger = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearLedger() {

            ledger_ = 0;
            onChanged();
            return this;
        }

        private int epoch_;

        /**
         * <code>int32 epoch = 2;</code>
         *
         * @return The epoch.
         */
        @java.lang.Override
        public int getEpoch() {
            return epoch_;
        }

        /**
         * <code>int32 epoch = 2;</code>
         *
         * @param value The epoch to set.
         * @return This builder for chaining.
         */
        public Builder setEpoch(int value) {

            epoch_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 epoch = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearEpoch() {

            epoch_ = 0;
            onChanged();
            return this;
        }

        private int index_;

        /**
         * <code>int32 index = 3;</code>
         *
         * @return The index.
         */
        @java.lang.Override
        public int getIndex() {
            return index_;
        }

        /**
         * <code>int32 index = 3;</code>
         *
         * @param value The index to set.
         * @return This builder for chaining.
         */
        public Builder setIndex(int value) {

            index_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 index = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearIndex() {

            index_ = 0;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:meteor.protobuf.MessageId)
  }

  // @@protoc_insertion_point(class_scope:meteor.protobuf.MessageId)
  private static final org.meteor.remote.proto.MessageId DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.meteor.remote.proto.MessageId();
  }

  public static org.meteor.remote.proto.MessageId getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageId>
      PARSER = new com.google.protobuf.AbstractParser<MessageId>() {
    @java.lang.Override
    public MessageId parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MessageId> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageId> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.meteor.remote.proto.MessageId getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

