// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meteor.proto

package org.meteor.remote.proto;

public final class MessageMetadataProto {
  private MessageMetadataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meteor_protobuf_MessageId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meteor_protobuf_MessageId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meteor_protobuf_MessageOffset_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meteor_protobuf_MessageOffset_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meteor_protobuf_MessageMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meteor_protobuf_MessageMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meteor_protobuf_MessageMetadata_ExtrasEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meteor_protobuf_MessageMetadata_ExtrasEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meteor_protobuf_ClusterMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meteor_protobuf_ClusterMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meteor_protobuf_NodeMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meteor_protobuf_NodeMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meteor_protobuf_ClusterInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meteor_protobuf_ClusterInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meteor_protobuf_ClusterInfo_NodesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meteor_protobuf_ClusterInfo_NodesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meteor_protobuf_TopicMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meteor_protobuf_TopicMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meteor_protobuf_PartitionMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meteor_protobuf_PartitionMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meteor_protobuf_TopicInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meteor_protobuf_TopicInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meteor_protobuf_TopicInfo_PartitionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meteor_protobuf_TopicInfo_PartitionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meteor_protobuf_TopicSegmentInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meteor_protobuf_TopicSegmentInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
            """
      
      meteor.protometeor.protobuf"9
      	Messa\
      geId
      ledger (
      epoch (
      i\
      ndex ("-
      
MessageOffset
      epoch \
      (
      index ("
      MessageMetadata
      topic (	
      queue (	<
      extras \
      (2,.meteor.protobuf.MessageMetadata.Ex\
      trasEntry-
      ExtrasEntry
      key (	
      value (	:8"
      ClusterMetadata
      n\
      ame (	"L
      NodeMetadata
      cluster_nam\
      e (	
      
      id (	
      host (	
      por\
      t ("Å
      ClusterInfo1
      cluster (\
      2 .meteor.protobuf.ClusterMetadata6
      no\
      des (2'.meteor.protobuf.ClusterInfo.\
      NodesEntryK
      
      NodesEntry
      key (	,
      value (2.meteor.protobuf.NodeMetad\
      ata:8":
      
TopicMetadata
      name (	
      
      id (
      version ("
      Partitio\
      nMetadata
      
      topic_name (	
      
      id (\
      
      ledger (
      epoch (
      lead\
      er_node_id (	
      replica_node_ids \
      (	
      version ("Ñ
      	TopicInfo-
      top\
      ic (2.meteor.protobuf.TopicMetadata\
      >
      
      partitions (2*.meteor.protobuf.T\
      opicInfo.PartitionsEntryU
      PartitionsEn\
      try
      key (1
      value (2".meteor\
      .protobuf.PartitionMetadata:8"u
      Topic\
      SegmentInfo
      segmentRollingSize (\
      
      segmentRetainCount (
      segmentRe\
      tainMs (
      allocate (B1
      org.me\
      teor.remote.protoBMessageMetadataProtoP\
      bproto3"""
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_meteor_protobuf_MessageId_descriptor =
            getDescriptor().getMessageTypes().getFirst();
    internal_static_meteor_protobuf_MessageId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meteor_protobuf_MessageId_descriptor,
        new java.lang.String[] { "Ledger", "Epoch", "Index", });
    internal_static_meteor_protobuf_MessageOffset_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_meteor_protobuf_MessageOffset_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meteor_protobuf_MessageOffset_descriptor,
        new java.lang.String[] { "Epoch", "Index", });
    internal_static_meteor_protobuf_MessageMetadata_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_meteor_protobuf_MessageMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meteor_protobuf_MessageMetadata_descriptor,
        new java.lang.String[] { "Topic", "Queue", "Extras", });
    internal_static_meteor_protobuf_MessageMetadata_ExtrasEntry_descriptor =
            internal_static_meteor_protobuf_MessageMetadata_descriptor.getNestedTypes().getFirst();
    internal_static_meteor_protobuf_MessageMetadata_ExtrasEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meteor_protobuf_MessageMetadata_ExtrasEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_meteor_protobuf_ClusterMetadata_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_meteor_protobuf_ClusterMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meteor_protobuf_ClusterMetadata_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_meteor_protobuf_NodeMetadata_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_meteor_protobuf_NodeMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meteor_protobuf_NodeMetadata_descriptor,
        new java.lang.String[] { "ClusterName", "Id", "Host", "Port", });
    internal_static_meteor_protobuf_ClusterInfo_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_meteor_protobuf_ClusterInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meteor_protobuf_ClusterInfo_descriptor,
        new java.lang.String[] { "Cluster", "Nodes", });
    internal_static_meteor_protobuf_ClusterInfo_NodesEntry_descriptor =
            internal_static_meteor_protobuf_ClusterInfo_descriptor.getNestedTypes().getFirst();
    internal_static_meteor_protobuf_ClusterInfo_NodesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meteor_protobuf_ClusterInfo_NodesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_meteor_protobuf_TopicMetadata_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_meteor_protobuf_TopicMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meteor_protobuf_TopicMetadata_descriptor,
        new java.lang.String[] { "Name", "Id", "Version", });
    internal_static_meteor_protobuf_PartitionMetadata_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_meteor_protobuf_PartitionMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meteor_protobuf_PartitionMetadata_descriptor,
        new java.lang.String[] { "TopicName", "Id", "Ledger", "Epoch", "LeaderNodeId", "ReplicaNodeIds", "Version", });
    internal_static_meteor_protobuf_TopicInfo_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_meteor_protobuf_TopicInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meteor_protobuf_TopicInfo_descriptor,
        new java.lang.String[] { "Topic", "Partitions", });
    internal_static_meteor_protobuf_TopicInfo_PartitionsEntry_descriptor =
            internal_static_meteor_protobuf_TopicInfo_descriptor.getNestedTypes().getFirst();
    internal_static_meteor_protobuf_TopicInfo_PartitionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meteor_protobuf_TopicInfo_PartitionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_meteor_protobuf_TopicSegmentInfo_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_meteor_protobuf_TopicSegmentInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meteor_protobuf_TopicSegmentInfo_descriptor,
        new java.lang.String[] { "SegmentRollingSize", "SegmentRetainCount", "SegmentRetainMs", "Allocate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
