// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meteor.proto

package org.meteor.remote.proto;

/**
 * Protobuf type {@code meteor.protobuf.TopicSegmentInfo}
 */
public final class TopicSegmentInfo extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:meteor.protobuf.TopicSegmentInfo)
        TopicSegmentInfoOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use TopicSegmentInfo.newBuilder() to construct.
    private TopicSegmentInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private TopicSegmentInfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new TopicSegmentInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return org.meteor.remote.proto.MessageMetadataProto.internal_static_meteor_protobuf_TopicSegmentInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return org.meteor.remote.proto.MessageMetadataProto.internal_static_meteor_protobuf_TopicSegmentInfo_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        org.meteor.remote.proto.TopicSegmentInfo.class,
                        org.meteor.remote.proto.TopicSegmentInfo.Builder.class);
    }

    public static final int SEGMENTROLLINGSIZE_FIELD_NUMBER = 1;
    private int segmentRollingSize_;

    /**
     * <code>int32 segmentRollingSize = 1;</code>
     *
     * @return The segmentRollingSize.
     */
    @java.lang.Override
    public int getSegmentRollingSize() {
        return segmentRollingSize_;
    }

    public static final int SEGMENTRETAINCOUNT_FIELD_NUMBER = 2;
    private int segmentRetainCount_;

    /**
     * <code>int32 segmentRetainCount = 2;</code>
     *
     * @return The segmentRetainCount.
     */
    @java.lang.Override
    public int getSegmentRetainCount() {
        return segmentRetainCount_;
    }

    public static final int SEGMENTRETAINMS_FIELD_NUMBER = 3;
    private int segmentRetainMs_;

    /**
     * <code>int32 segmentRetainMs = 3;</code>
     *
     * @return The segmentRetainMs.
     */
    @java.lang.Override
    public int getSegmentRetainMs() {
        return segmentRetainMs_;
    }

    public static final int ALLOCATE_FIELD_NUMBER = 4;
    private boolean allocate_;

    /**
     * <code>bool allocate = 4;</code>
     *
     * @return The allocate.
     */
    @java.lang.Override
    public boolean getAllocate() {
        return allocate_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) {
            return true;
        }
        if (isInitialized == 0) {
            return false;
        }

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (segmentRollingSize_ != 0) {
            output.writeInt32(1, segmentRollingSize_);
        }
        if (segmentRetainCount_ != 0) {
            output.writeInt32(2, segmentRetainCount_);
        }
        if (segmentRetainMs_ != 0) {
            output.writeInt32(3, segmentRetainMs_);
        }
        if (allocate_ != false) {
            output.writeBool(4, allocate_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) {
            return size;
        }

        size = 0;
        if (segmentRollingSize_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(1, segmentRollingSize_);
        }
        if (segmentRetainCount_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(2, segmentRetainCount_);
        }
        if (segmentRetainMs_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(3, segmentRetainMs_);
        }
        if (allocate_ != false) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBoolSize(4, allocate_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof org.meteor.remote.proto.TopicSegmentInfo)) {
            return super.equals(obj);
        }
        org.meteor.remote.proto.TopicSegmentInfo other = (org.meteor.remote.proto.TopicSegmentInfo) obj;

        if (getSegmentRollingSize()
                != other.getSegmentRollingSize()) {
            return false;
        }
        if (getSegmentRetainCount()
                != other.getSegmentRetainCount()) {
            return false;
        }
        if (getSegmentRetainMs()
                != other.getSegmentRetainMs()) {
            return false;
        }
        if (getAllocate()
                != other.getAllocate()) {
            return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) {
            return false;
        }
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SEGMENTROLLINGSIZE_FIELD_NUMBER;
        hash = (53 * hash) + getSegmentRollingSize();
        hash = (37 * hash) + SEGMENTRETAINCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getSegmentRetainCount();
        hash = (37 * hash) + SEGMENTRETAINMS_FIELD_NUMBER;
        hash = (53 * hash) + getSegmentRetainMs();
        hash = (37 * hash) + ALLOCATE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                getAllocate());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static org.meteor.remote.proto.TopicSegmentInfo parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.meteor.remote.proto.TopicSegmentInfo parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.meteor.remote.proto.TopicSegmentInfo parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.meteor.remote.proto.TopicSegmentInfo parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.meteor.remote.proto.TopicSegmentInfo parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.meteor.remote.proto.TopicSegmentInfo parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.meteor.remote.proto.TopicSegmentInfo parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static org.meteor.remote.proto.TopicSegmentInfo parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.meteor.remote.proto.TopicSegmentInfo parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.meteor.remote.proto.TopicSegmentInfo parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.meteor.remote.proto.TopicSegmentInfo parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static org.meteor.remote.proto.TopicSegmentInfo parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(org.meteor.remote.proto.TopicSegmentInfo prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code meteor.protobuf.TopicSegmentInfo}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:meteor.protobuf.TopicSegmentInfo)
            org.meteor.remote.proto.TopicSegmentInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return org.meteor.remote.proto.MessageMetadataProto.internal_static_meteor_protobuf_TopicSegmentInfo_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return org.meteor.remote.proto.MessageMetadataProto.internal_static_meteor_protobuf_TopicSegmentInfo_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.meteor.remote.proto.TopicSegmentInfo.class,
                            org.meteor.remote.proto.TopicSegmentInfo.Builder.class);
        }

        // Construct using org.meteor.remote.proto.TopicSegmentInfo.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);

        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            segmentRollingSize_ = 0;

      segmentRetainCount_ = 0;

      segmentRetainMs_ = 0;

      allocate_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
        return org.meteor.remote.proto.MessageMetadataProto.internal_static_meteor_protobuf_TopicSegmentInfo_descriptor;
    }

        @java.lang.Override
        public org.meteor.remote.proto.TopicSegmentInfo getDefaultInstanceForType() {
            return org.meteor.remote.proto.TopicSegmentInfo.getDefaultInstance();
        }

        @java.lang.Override
        public org.meteor.remote.proto.TopicSegmentInfo build() {
            org.meteor.remote.proto.TopicSegmentInfo result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public org.meteor.remote.proto.TopicSegmentInfo buildPartial() {
            org.meteor.remote.proto.TopicSegmentInfo result = new org.meteor.remote.proto.TopicSegmentInfo(this);
            result.segmentRollingSize_ = segmentRollingSize_;
            result.segmentRetainCount_ = segmentRetainCount_;
            result.segmentRetainMs_ = segmentRetainMs_;
            result.allocate_ = allocate_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof org.meteor.remote.proto.TopicSegmentInfo) {
                return mergeFrom((org.meteor.remote.proto.TopicSegmentInfo) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(org.meteor.remote.proto.TopicSegmentInfo other) {
            if (other == org.meteor.remote.proto.TopicSegmentInfo.getDefaultInstance()) {
                return this;
            }
            if (other.getSegmentRollingSize() != 0) {
                setSegmentRollingSize(other.getSegmentRollingSize());
            }
            if (other.getSegmentRetainCount() != 0) {
                setSegmentRetainCount(other.getSegmentRetainCount());
            }
            if (other.getSegmentRetainMs() != 0) {
                setSegmentRetainMs(other.getSegmentRetainMs());
            }
            if (other.getAllocate() != false) {
                setAllocate(other.getAllocate());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            segmentRollingSize_ = input.readInt32();

                            break;
                        } // case 8
                        case 16: {
                            segmentRetainCount_ = input.readInt32();

                            break;
                        } // case 16
                        case 24: {
                            segmentRetainMs_ = input.readInt32();

                            break;
                        } // case 24
                        case 32: {
                            allocate_ = input.readBool();

                            break;
                        } // case 32
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int segmentRollingSize_;

        /**
         * <code>int32 segmentRollingSize = 1;</code>
         *
         * @return The segmentRollingSize.
         */
        @java.lang.Override
        public int getSegmentRollingSize() {
            return segmentRollingSize_;
        }

        /**
         * <code>int32 segmentRollingSize = 1;</code>
         *
         * @param value The segmentRollingSize to set.
         * @return This builder for chaining.
         */
        public Builder setSegmentRollingSize(int value) {

            segmentRollingSize_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 segmentRollingSize = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSegmentRollingSize() {

            segmentRollingSize_ = 0;
            onChanged();
            return this;
        }

        private int segmentRetainCount_;

        /**
         * <code>int32 segmentRetainCount = 2;</code>
         *
         * @return The segmentRetainCount.
         */
        @java.lang.Override
        public int getSegmentRetainCount() {
            return segmentRetainCount_;
        }

        /**
         * <code>int32 segmentRetainCount = 2;</code>
         *
         * @param value The segmentRetainCount to set.
         * @return This builder for chaining.
         */
        public Builder setSegmentRetainCount(int value) {

            segmentRetainCount_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 segmentRetainCount = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSegmentRetainCount() {

            segmentRetainCount_ = 0;
            onChanged();
            return this;
        }

        private int segmentRetainMs_;

        /**
         * <code>int32 segmentRetainMs = 3;</code>
         *
         * @return The segmentRetainMs.
         */
        @java.lang.Override
        public int getSegmentRetainMs() {
            return segmentRetainMs_;
        }

        /**
         * <code>int32 segmentRetainMs = 3;</code>
         *
         * @param value The segmentRetainMs to set.
         * @return This builder for chaining.
         */
        public Builder setSegmentRetainMs(int value) {

            segmentRetainMs_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 segmentRetainMs = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSegmentRetainMs() {

            segmentRetainMs_ = 0;
            onChanged();
            return this;
        }

        private boolean allocate_;

        /**
         * <code>bool allocate = 4;</code>
         *
         * @return The allocate.
         */
        @java.lang.Override
        public boolean getAllocate() {
            return allocate_;
        }

        /**
         * <code>bool allocate = 4;</code>
         *
         * @param value The allocate to set.
         * @return This builder for chaining.
         */
        public Builder setAllocate(boolean value) {

            allocate_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>bool allocate = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearAllocate() {

            allocate_ = false;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:meteor.protobuf.TopicSegmentInfo)
    }

    // @@protoc_insertion_point(class_scope:meteor.protobuf.TopicSegmentInfo)
    private static final org.meteor.remote.proto.TopicSegmentInfo DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new org.meteor.remote.proto.TopicSegmentInfo();
    }

    public static org.meteor.remote.proto.TopicSegmentInfo getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TopicSegmentInfo>
            PARSER = new com.google.protobuf.AbstractParser<TopicSegmentInfo>() {
        @java.lang.Override
    public TopicSegmentInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TopicSegmentInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TopicSegmentInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.meteor.remote.proto.TopicSegmentInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

