// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat.proto

package org.shallow.proto.heartbeat;

public interface HeartbeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shallow.protobuf.HeartbeatResponse)
    com.google.protobuf.MessageOrBuilder {
}
