// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.meteor.remote.proto.server;

public interface CreateTopicRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:meteor.protobuf.CreateTopicRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string topic = 1;</code>
     *
     * @return The topic.
     */
    java.lang.String getTopic();

    /**
     * <code>string topic = 1;</code>
     *
     * @return The bytes for topic.
     */
    com.google.protobuf.ByteString
    getTopicBytes();

    /**
     * <code>int32 partition = 2;</code>
     * @return The partition.
     */
    int getPartition();

    /**
     * <code>int32 replicas = 3;</code>
     * @return The replicas.
     */
    int getReplicas();

    /**
     * <code>.meteor.protobuf.CreateTopicConfigRequest configs = 4;</code>
     *
     * @return Whether the configs field is set.
     */
    boolean hasConfigs();

    /**
     * <code>.meteor.protobuf.CreateTopicConfigRequest configs = 4;</code>
     *
     * @return The configs.
     */
    org.meteor.remote.proto.server.CreateTopicConfigRequest getConfigs();

    /**
     * <code>.meteor.protobuf.CreateTopicConfigRequest configs = 4;</code>
     */
    org.meteor.remote.proto.server.CreateTopicConfigRequestOrBuilder getConfigsOrBuilder();
}
