// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.meteor.remote.proto.server;

/**
 * Protobuf type {@code meteor.protobuf.SyncResponse}
 */
public final class SyncResponse extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:meteor.protobuf.SyncResponse)
        SyncResponseOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use SyncResponse.newBuilder() to construct.
    private SyncResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private SyncResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new SyncResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return org.meteor.remote.proto.server.ServerProto.internal_static_meteor_protobuf_SyncResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return org.meteor.remote.proto.server.ServerProto.internal_static_meteor_protobuf_SyncResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        org.meteor.remote.proto.server.SyncResponse.class,
                        org.meteor.remote.proto.server.SyncResponse.Builder.class);
    }

    public static final int CURRENTOFFSET_FIELD_NUMBER = 1;
    private org.meteor.remote.proto.MessageOffset currentOffset_;

    /**
     * <code>.meteor.protobuf.MessageOffset currentOffset = 1;</code>
     *
     * @return Whether the currentOffset field is set.
     */
    @java.lang.Override
    public boolean hasCurrentOffset() {
        return currentOffset_ != null;
    }

    /**
     * <code>.meteor.protobuf.MessageOffset currentOffset = 1;</code>
     *
     * @return The currentOffset.
     */
    @java.lang.Override
    public org.meteor.remote.proto.MessageOffset getCurrentOffset() {
        return currentOffset_ == null ? org.meteor.remote.proto.MessageOffset.getDefaultInstance() : currentOffset_;
    }

    /**
     * <code>.meteor.protobuf.MessageOffset currentOffset = 1;</code>
     */
    @java.lang.Override
    public org.meteor.remote.proto.MessageOffsetOrBuilder getCurrentOffsetOrBuilder() {
        return getCurrentOffset();
    }

    public static final int HEADOFFSET_FIELD_NUMBER = 2;
    private org.meteor.remote.proto.MessageOffset headOffset_;

    /**
     * <code>.meteor.protobuf.MessageOffset headOffset = 2;</code>
     *
     * @return Whether the headOffset field is set.
     */
    @java.lang.Override
    public boolean hasHeadOffset() {
        return headOffset_ != null;
    }

    /**
     * <code>.meteor.protobuf.MessageOffset headOffset = 2;</code>
     *
     * @return The headOffset.
     */
    @java.lang.Override
    public org.meteor.remote.proto.MessageOffset getHeadOffset() {
        return headOffset_ == null ? org.meteor.remote.proto.MessageOffset.getDefaultInstance() : headOffset_;
    }

    /**
     * <code>.meteor.protobuf.MessageOffset headOffset = 2;</code>
     */
    @java.lang.Override
    public org.meteor.remote.proto.MessageOffsetOrBuilder getHeadOffsetOrBuilder() {
        return getHeadOffset();
    }

    public static final int TAILOFFSET_FIELD_NUMBER = 3;
    private org.meteor.remote.proto.MessageOffset tailOffset_;

    /**
     * <code>.meteor.protobuf.MessageOffset tailOffset = 3;</code>
     *
     * @return Whether the tailOffset field is set.
     */
    @java.lang.Override
    public boolean hasTailOffset() {
        return tailOffset_ != null;
    }

    /**
     * <code>.meteor.protobuf.MessageOffset tailOffset = 3;</code>
     *
     * @return The tailOffset.
     */
    @java.lang.Override
    public org.meteor.remote.proto.MessageOffset getTailOffset() {
        return tailOffset_ == null ? org.meteor.remote.proto.MessageOffset.getDefaultInstance() : tailOffset_;
    }

    /**
     * <code>.meteor.protobuf.MessageOffset tailOffset = 3;</code>
     */
    @java.lang.Override
    public org.meteor.remote.proto.MessageOffsetOrBuilder getTailOffsetOrBuilder() {
        return getTailOffset();
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) {
            return true;
        }
        if (isInitialized == 0) {
            return false;
        }

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (currentOffset_ != null) {
            output.writeMessage(1, getCurrentOffset());
        }
        if (headOffset_ != null) {
            output.writeMessage(2, getHeadOffset());
        }
        if (tailOffset_ != null) {
            output.writeMessage(3, getTailOffset());
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) {
            return size;
        }

        size = 0;
        if (currentOffset_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, getCurrentOffset());
        }
        if (headOffset_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(2, getHeadOffset());
        }
        if (tailOffset_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(3, getTailOffset());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof org.meteor.remote.proto.server.SyncResponse)) {
            return super.equals(obj);
        }
        org.meteor.remote.proto.server.SyncResponse other = (org.meteor.remote.proto.server.SyncResponse) obj;

        if (hasCurrentOffset() != other.hasCurrentOffset()) {
            return false;
        }
        if (hasCurrentOffset()) {
            if (!getCurrentOffset()
                    .equals(other.getCurrentOffset())) {
                return false;
            }
        }
        if (hasHeadOffset() != other.hasHeadOffset()) {
            return false;
        }
        if (hasHeadOffset()) {
            if (!getHeadOffset()
                    .equals(other.getHeadOffset())) {
                return false;
            }
        }
        if (hasTailOffset() != other.hasTailOffset()) {
            return false;
        }
        if (hasTailOffset()) {
            if (!getTailOffset()
                    .equals(other.getTailOffset())) {
                return false;
            }
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) {
            return false;
        }
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasCurrentOffset()) {
            hash = (37 * hash) + CURRENTOFFSET_FIELD_NUMBER;
            hash = (53 * hash) + getCurrentOffset().hashCode();
        }
        if (hasHeadOffset()) {
            hash = (37 * hash) + HEADOFFSET_FIELD_NUMBER;
            hash = (53 * hash) + getHeadOffset().hashCode();
        }
        if (hasTailOffset()) {
            hash = (37 * hash) + TAILOFFSET_FIELD_NUMBER;
            hash = (53 * hash) + getTailOffset().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static org.meteor.remote.proto.server.SyncResponse parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.meteor.remote.proto.server.SyncResponse parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.meteor.remote.proto.server.SyncResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.meteor.remote.proto.server.SyncResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.meteor.remote.proto.server.SyncResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.meteor.remote.proto.server.SyncResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.meteor.remote.proto.server.SyncResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static org.meteor.remote.proto.server.SyncResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.meteor.remote.proto.server.SyncResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.meteor.remote.proto.server.SyncResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.meteor.remote.proto.server.SyncResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static org.meteor.remote.proto.server.SyncResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(org.meteor.remote.proto.server.SyncResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code meteor.protobuf.SyncResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:meteor.protobuf.SyncResponse)
            org.meteor.remote.proto.server.SyncResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return org.meteor.remote.proto.server.ServerProto.internal_static_meteor_protobuf_SyncResponse_descriptor;
    }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return org.meteor.remote.proto.server.ServerProto.internal_static_meteor_protobuf_SyncResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.meteor.remote.proto.server.SyncResponse.class,
                            org.meteor.remote.proto.server.SyncResponse.Builder.class);
        }

        // Construct using org.meteor.remote.proto.server.SyncResponse.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);

        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            if (currentOffsetBuilder_ == null) {
                currentOffset_ = null;
            } else {
                currentOffset_ = null;
                currentOffsetBuilder_ = null;
            }
            if (headOffsetBuilder_ == null) {
                headOffset_ = null;
            } else {
                headOffset_ = null;
                headOffsetBuilder_ = null;
      }
      if (tailOffsetBuilder_ == null) {
        tailOffset_ = null;
      } else {
          tailOffset_ = null;
          tailOffsetBuilder_ = null;
      }
            return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
        return org.meteor.remote.proto.server.ServerProto.internal_static_meteor_protobuf_SyncResponse_descriptor;
    }

        @java.lang.Override
        public org.meteor.remote.proto.server.SyncResponse getDefaultInstanceForType() {
            return org.meteor.remote.proto.server.SyncResponse.getDefaultInstance();
        }

        @java.lang.Override
        public org.meteor.remote.proto.server.SyncResponse build() {
            org.meteor.remote.proto.server.SyncResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public org.meteor.remote.proto.server.SyncResponse buildPartial() {
            org.meteor.remote.proto.server.SyncResponse result = new org.meteor.remote.proto.server.SyncResponse(this);
            if (currentOffsetBuilder_ == null) {
                result.currentOffset_ = currentOffset_;
            } else {
                result.currentOffset_ = currentOffsetBuilder_.build();
            }
            if (headOffsetBuilder_ == null) {
                result.headOffset_ = headOffset_;
            } else {
                result.headOffset_ = headOffsetBuilder_.build();
            }
            if (tailOffsetBuilder_ == null) {
                result.tailOffset_ = tailOffset_;
            } else {
                result.tailOffset_ = tailOffsetBuilder_.build();
            }
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof org.meteor.remote.proto.server.SyncResponse) {
                return mergeFrom((org.meteor.remote.proto.server.SyncResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(org.meteor.remote.proto.server.SyncResponse other) {
            if (other == org.meteor.remote.proto.server.SyncResponse.getDefaultInstance()) {
                return this;
            }
            if (other.hasCurrentOffset()) {
                mergeCurrentOffset(other.getCurrentOffset());
            }
            if (other.hasHeadOffset()) {
                mergeHeadOffset(other.getHeadOffset());
            }
            if (other.hasTailOffset()) {
                mergeTailOffset(other.getTailOffset());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            input.readMessage(
                                    getCurrentOffsetFieldBuilder().getBuilder(),
                                    extensionRegistry);

                            break;
                        } // case 10
                        case 18: {
                            input.readMessage(
                                    getHeadOffsetFieldBuilder().getBuilder(),
                                    extensionRegistry);

                            break;
                        } // case 18
                        case 26: {
                            input.readMessage(
                                    getTailOffsetFieldBuilder().getBuilder(),
                                    extensionRegistry);

                            break;
                        } // case 26
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private org.meteor.remote.proto.MessageOffset currentOffset_;
        private com.google.protobuf.SingleFieldBuilderV3<
                org.meteor.remote.proto.MessageOffset, org.meteor.remote.proto.MessageOffset.Builder, org.meteor.remote.proto.MessageOffsetOrBuilder>
                currentOffsetBuilder_;

        /**
         * <code>.meteor.protobuf.MessageOffset currentOffset = 1;</code>
         *
         * @return Whether the currentOffset field is set.
         */
        public boolean hasCurrentOffset() {
            return currentOffsetBuilder_ != null || currentOffset_ != null;
        }

        /**
         * <code>.meteor.protobuf.MessageOffset currentOffset = 1;</code>
         *
         * @return The currentOffset.
         */
        public org.meteor.remote.proto.MessageOffset getCurrentOffset() {
            if (currentOffsetBuilder_ == null) {
                return currentOffset_ == null ? org.meteor.remote.proto.MessageOffset.getDefaultInstance() :
                        currentOffset_;
            } else {
                return currentOffsetBuilder_.getMessage();
            }
        }

        /**
         * <code>.meteor.protobuf.MessageOffset currentOffset = 1;</code>
         */
        public Builder setCurrentOffset(org.meteor.remote.proto.MessageOffset value) {
            if (currentOffsetBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                currentOffset_ = value;
                onChanged();
            } else {
                currentOffsetBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.meteor.protobuf.MessageOffset currentOffset = 1;</code>
         */
        public Builder setCurrentOffset(
                org.meteor.remote.proto.MessageOffset.Builder builderForValue) {
            if (currentOffsetBuilder_ == null) {
                currentOffset_ = builderForValue.build();
                onChanged();
            } else {
                currentOffsetBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.meteor.protobuf.MessageOffset currentOffset = 1;</code>
         */
        public Builder mergeCurrentOffset(org.meteor.remote.proto.MessageOffset value) {
            if (currentOffsetBuilder_ == null) {
                if (currentOffset_ != null) {
                    currentOffset_ =
                            org.meteor.remote.proto.MessageOffset.newBuilder(currentOffset_).mergeFrom(value)
                                    .buildPartial();
                } else {
                    currentOffset_ = value;
                }
                onChanged();
            } else {
                currentOffsetBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.meteor.protobuf.MessageOffset currentOffset = 1;</code>
         */
        public Builder clearCurrentOffset() {
            if (currentOffsetBuilder_ == null) {
                currentOffset_ = null;
                onChanged();
            } else {
                currentOffset_ = null;
                currentOffsetBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.meteor.protobuf.MessageOffset currentOffset = 1;</code>
         */
        public org.meteor.remote.proto.MessageOffset.Builder getCurrentOffsetBuilder() {

            onChanged();
            return getCurrentOffsetFieldBuilder().getBuilder();
        }

        /**
         * <code>.meteor.protobuf.MessageOffset currentOffset = 1;</code>
         */
        public org.meteor.remote.proto.MessageOffsetOrBuilder getCurrentOffsetOrBuilder() {
            if (currentOffsetBuilder_ != null) {
                return currentOffsetBuilder_.getMessageOrBuilder();
            } else {
                return currentOffset_ == null ?
                        org.meteor.remote.proto.MessageOffset.getDefaultInstance() : currentOffset_;
            }
        }

        /**
         * <code>.meteor.protobuf.MessageOffset currentOffset = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                org.meteor.remote.proto.MessageOffset, org.meteor.remote.proto.MessageOffset.Builder, org.meteor.remote.proto.MessageOffsetOrBuilder>
        getCurrentOffsetFieldBuilder() {
            if (currentOffsetBuilder_ == null) {
                currentOffsetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        org.meteor.remote.proto.MessageOffset, org.meteor.remote.proto.MessageOffset.Builder, org.meteor.remote.proto.MessageOffsetOrBuilder>(
                        getCurrentOffset(),
                        getParentForChildren(),
                        isClean());
                currentOffset_ = null;
            }
            return currentOffsetBuilder_;
        }

        private org.meteor.remote.proto.MessageOffset headOffset_;
        private com.google.protobuf.SingleFieldBuilderV3<
                org.meteor.remote.proto.MessageOffset, org.meteor.remote.proto.MessageOffset.Builder, org.meteor.remote.proto.MessageOffsetOrBuilder>
                headOffsetBuilder_;

        /**
         * <code>.meteor.protobuf.MessageOffset headOffset = 2;</code>
         *
         * @return Whether the headOffset field is set.
         */
        public boolean hasHeadOffset() {
            return headOffsetBuilder_ != null || headOffset_ != null;
        }

        /**
         * <code>.meteor.protobuf.MessageOffset headOffset = 2;</code>
         *
         * @return The headOffset.
         */
        public org.meteor.remote.proto.MessageOffset getHeadOffset() {
            if (headOffsetBuilder_ == null) {
                return headOffset_ == null ? org.meteor.remote.proto.MessageOffset.getDefaultInstance() : headOffset_;
            } else {
                return headOffsetBuilder_.getMessage();
            }
        }

        /**
         * <code>.meteor.protobuf.MessageOffset headOffset = 2;</code>
         */
        public Builder setHeadOffset(org.meteor.remote.proto.MessageOffset value) {
            if (headOffsetBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                headOffset_ = value;
                onChanged();
            } else {
                headOffsetBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.meteor.protobuf.MessageOffset headOffset = 2;</code>
         */
        public Builder setHeadOffset(
                org.meteor.remote.proto.MessageOffset.Builder builderForValue) {
            if (headOffsetBuilder_ == null) {
                headOffset_ = builderForValue.build();
                onChanged();
            } else {
                headOffsetBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.meteor.protobuf.MessageOffset headOffset = 2;</code>
         */
        public Builder mergeHeadOffset(org.meteor.remote.proto.MessageOffset value) {
            if (headOffsetBuilder_ == null) {
                if (headOffset_ != null) {
                    headOffset_ =
                            org.meteor.remote.proto.MessageOffset.newBuilder(headOffset_).mergeFrom(value)
                                    .buildPartial();
                } else {
                    headOffset_ = value;
                }
                onChanged();
            } else {
                headOffsetBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.meteor.protobuf.MessageOffset headOffset = 2;</code>
         */
        public Builder clearHeadOffset() {
            if (headOffsetBuilder_ == null) {
                headOffset_ = null;
                onChanged();
            } else {
                headOffset_ = null;
                headOffsetBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.meteor.protobuf.MessageOffset headOffset = 2;</code>
         */
        public org.meteor.remote.proto.MessageOffset.Builder getHeadOffsetBuilder() {

            onChanged();
            return getHeadOffsetFieldBuilder().getBuilder();
        }

        /**
         * <code>.meteor.protobuf.MessageOffset headOffset = 2;</code>
         */
        public org.meteor.remote.proto.MessageOffsetOrBuilder getHeadOffsetOrBuilder() {
            if (headOffsetBuilder_ != null) {
                return headOffsetBuilder_.getMessageOrBuilder();
            } else {
                return headOffset_ == null ?
                        org.meteor.remote.proto.MessageOffset.getDefaultInstance() : headOffset_;
            }
        }

        /**
         * <code>.meteor.protobuf.MessageOffset headOffset = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                org.meteor.remote.proto.MessageOffset, org.meteor.remote.proto.MessageOffset.Builder, org.meteor.remote.proto.MessageOffsetOrBuilder>
        getHeadOffsetFieldBuilder() {
            if (headOffsetBuilder_ == null) {
                headOffsetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        org.meteor.remote.proto.MessageOffset, org.meteor.remote.proto.MessageOffset.Builder, org.meteor.remote.proto.MessageOffsetOrBuilder>(
                        getHeadOffset(),
                        getParentForChildren(),
                        isClean());
                headOffset_ = null;
            }
            return headOffsetBuilder_;
        }

        private org.meteor.remote.proto.MessageOffset tailOffset_;
        private com.google.protobuf.SingleFieldBuilderV3<
                org.meteor.remote.proto.MessageOffset, org.meteor.remote.proto.MessageOffset.Builder, org.meteor.remote.proto.MessageOffsetOrBuilder>
                tailOffsetBuilder_;

        /**
         * <code>.meteor.protobuf.MessageOffset tailOffset = 3;</code>
         *
         * @return Whether the tailOffset field is set.
         */
        public boolean hasTailOffset() {
            return tailOffsetBuilder_ != null || tailOffset_ != null;
        }

        /**
         * <code>.meteor.protobuf.MessageOffset tailOffset = 3;</code>
         *
         * @return The tailOffset.
         */
        public org.meteor.remote.proto.MessageOffset getTailOffset() {
            if (tailOffsetBuilder_ == null) {
                return tailOffset_ == null ? org.meteor.remote.proto.MessageOffset.getDefaultInstance() : tailOffset_;
            } else {
                return tailOffsetBuilder_.getMessage();
            }
        }

        /**
         * <code>.meteor.protobuf.MessageOffset tailOffset = 3;</code>
         */
        public Builder setTailOffset(org.meteor.remote.proto.MessageOffset value) {
            if (tailOffsetBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                tailOffset_ = value;
                onChanged();
            } else {
                tailOffsetBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.meteor.protobuf.MessageOffset tailOffset = 3;</code>
         */
        public Builder setTailOffset(
                org.meteor.remote.proto.MessageOffset.Builder builderForValue) {
            if (tailOffsetBuilder_ == null) {
                tailOffset_ = builderForValue.build();
                onChanged();
            } else {
                tailOffsetBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.meteor.protobuf.MessageOffset tailOffset = 3;</code>
         */
        public Builder mergeTailOffset(org.meteor.remote.proto.MessageOffset value) {
            if (tailOffsetBuilder_ == null) {
                if (tailOffset_ != null) {
                    tailOffset_ =
                            org.meteor.remote.proto.MessageOffset.newBuilder(tailOffset_).mergeFrom(value)
                                    .buildPartial();
                } else {
                    tailOffset_ = value;
                }
                onChanged();
            } else {
                tailOffsetBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.meteor.protobuf.MessageOffset tailOffset = 3;</code>
         */
        public Builder clearTailOffset() {
            if (tailOffsetBuilder_ == null) {
                tailOffset_ = null;
                onChanged();
            } else {
                tailOffset_ = null;
                tailOffsetBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.meteor.protobuf.MessageOffset tailOffset = 3;</code>
         */
        public org.meteor.remote.proto.MessageOffset.Builder getTailOffsetBuilder() {

            onChanged();
            return getTailOffsetFieldBuilder().getBuilder();
        }

        /**
         * <code>.meteor.protobuf.MessageOffset tailOffset = 3;</code>
         */
        public org.meteor.remote.proto.MessageOffsetOrBuilder getTailOffsetOrBuilder() {
            if (tailOffsetBuilder_ != null) {
                return tailOffsetBuilder_.getMessageOrBuilder();
            } else {
                return tailOffset_ == null ?
                        org.meteor.remote.proto.MessageOffset.getDefaultInstance() : tailOffset_;
            }
        }

        /**
         * <code>.meteor.protobuf.MessageOffset tailOffset = 3;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                org.meteor.remote.proto.MessageOffset, org.meteor.remote.proto.MessageOffset.Builder, org.meteor.remote.proto.MessageOffsetOrBuilder>
        getTailOffsetFieldBuilder() {
            if (tailOffsetBuilder_ == null) {
                tailOffsetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        org.meteor.remote.proto.MessageOffset, org.meteor.remote.proto.MessageOffset.Builder, org.meteor.remote.proto.MessageOffsetOrBuilder>(
                        getTailOffset(),
                        getParentForChildren(),
                        isClean());
                tailOffset_ = null;
            }
            return tailOffsetBuilder_;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:meteor.protobuf.SyncResponse)
    }

    // @@protoc_insertion_point(class_scope:meteor.protobuf.SyncResponse)
    private static final org.meteor.remote.proto.server.SyncResponse DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new org.meteor.remote.proto.server.SyncResponse();
    }

    public static org.meteor.remote.proto.server.SyncResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SyncResponse>
            PARSER = new com.google.protobuf.AbstractParser<SyncResponse>() {
        @java.lang.Override
        public SyncResponse parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SyncResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SyncResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.meteor.remote.proto.server.SyncResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

