// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.ostara.remote.proto.server;

public interface AlterSubscribeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ostara.protobuf.AlterSubscribeResponse)
    com.google.protobuf.MessageOrBuilder {
}
