// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.ostara.remote.proto.server;

public interface PartitionsReplicasOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ostara.protobuf.PartitionsReplicas)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 partition = 1;</code>
     *
     * @return The partition.
     */
    int getPartition();

    /**
     * <code>repeated string replicas = 2;</code>
     *
     * @return A list containing the replicas.
     */
    java.util.List<java.lang.String>
    getReplicasList();

    /**
     * <code>repeated string replicas = 2;</code>
     *
     * @return The count of replicas.
     */
    int getReplicasCount();

    /**
     * <code>repeated string replicas = 2;</code>
     *
     * @param index The index of the element to return.
     * @return The replicas at the given index.
     */
    java.lang.String getReplicas(int index);

    /**
     * <code>repeated string replicas = 2;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the replicas at the given index.
     */
    com.google.protobuf.ByteString
    getReplicasBytes(int index);
}
