// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.ostara.remote.proto.server;

/**
 * Protobuf type {@code ostara.protobuf.RemoteCreateTopicRequest}
 */
public final class RemoteCreateTopicRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ostara.protobuf.RemoteCreateTopicRequest)
    RemoteCreateTopicRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RemoteCreateTopicRequest.newBuilder() to construct.
  private RemoteCreateTopicRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RemoteCreateTopicRequest() {
    topic_ = "";
    cluster_ = "";
    partitions_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RemoteCreateTopicRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.ostara.remote.proto.server.ServerProto.internal_static_ostara_protobuf_RemoteCreateTopicRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.ostara.remote.proto.server.ServerProto.internal_static_ostara_protobuf_RemoteCreateTopicRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.ostara.remote.proto.server.RemoteCreateTopicRequest.class, org.ostara.remote.proto.server.RemoteCreateTopicRequest.Builder.class);
  }

  public static final int TOPIC_FIELD_NUMBER = 1;
  private volatile java.lang.Object topic_;
  /**
   * <code>string topic = 1;</code>
   * @return The topic.
   */
  @java.lang.Override
  public java.lang.String getTopic() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topic_ = s;
      return s;
    }
  }
  /**
   * <code>string topic = 1;</code>
   * @return The bytes for topic.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTopicBytes() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLUSTER_FIELD_NUMBER = 2;
  private volatile java.lang.Object cluster_;
  /**
   * <code>string cluster = 2;</code>
   * @return The cluster.
   */
  @java.lang.Override
  public java.lang.String getCluster() {
    java.lang.Object ref = cluster_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cluster_ = s;
      return s;
    }
  }
  /**
   * <code>string cluster = 2;</code>
   * @return The bytes for cluster.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClusterBytes() {
    java.lang.Object ref = cluster_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cluster_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTITIONS_FIELD_NUMBER = 3;
  private java.util.List<org.ostara.remote.proto.PartitionMetadata> partitions_;
  /**
   * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
   */
  @java.lang.Override
  public java.util.List<org.ostara.remote.proto.PartitionMetadata> getPartitionsList() {
    return partitions_;
  }
  /**
   * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.ostara.remote.proto.PartitionMetadataOrBuilder> 
      getPartitionsOrBuilderList() {
    return partitions_;
  }
  /**
   * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
   */
  @java.lang.Override
  public int getPartitionsCount() {
    return partitions_.size();
  }
  /**
   * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
   */
  @java.lang.Override
  public org.ostara.remote.proto.PartitionMetadata getPartitions(int index) {
    return partitions_.get(index);
  }
  /**
   * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
   */
  @java.lang.Override
  public org.ostara.remote.proto.PartitionMetadataOrBuilder getPartitionsOrBuilder(
      int index) {
    return partitions_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, topic_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cluster_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cluster_);
    }
    for (int i = 0; i < partitions_.size(); i++) {
      output.writeMessage(3, partitions_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, topic_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cluster_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cluster_);
    }
    for (int i = 0; i < partitions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, partitions_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.ostara.remote.proto.server.RemoteCreateTopicRequest)) {
      return super.equals(obj);
    }
    org.ostara.remote.proto.server.RemoteCreateTopicRequest other = (org.ostara.remote.proto.server.RemoteCreateTopicRequest) obj;

    if (!getTopic()
        .equals(other.getTopic())) return false;
    if (!getCluster()
        .equals(other.getCluster())) return false;
    if (!getPartitionsList()
        .equals(other.getPartitionsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOPIC_FIELD_NUMBER;
    hash = (53 * hash) + getTopic().hashCode();
    hash = (37 * hash) + CLUSTER_FIELD_NUMBER;
    hash = (53 * hash) + getCluster().hashCode();
    if (getPartitionsCount() > 0) {
      hash = (37 * hash) + PARTITIONS_FIELD_NUMBER;
      hash = (53 * hash) + getPartitionsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.ostara.remote.proto.server.RemoteCreateTopicRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ostara.remote.proto.server.RemoteCreateTopicRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ostara.remote.proto.server.RemoteCreateTopicRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ostara.remote.proto.server.RemoteCreateTopicRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ostara.remote.proto.server.RemoteCreateTopicRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.ostara.remote.proto.server.RemoteCreateTopicRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.ostara.remote.proto.server.RemoteCreateTopicRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.ostara.remote.proto.server.RemoteCreateTopicRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ostara.remote.proto.server.RemoteCreateTopicRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.ostara.remote.proto.server.RemoteCreateTopicRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.ostara.remote.proto.server.RemoteCreateTopicRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.ostara.remote.proto.server.RemoteCreateTopicRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.ostara.remote.proto.server.RemoteCreateTopicRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ostara.protobuf.RemoteCreateTopicRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ostara.protobuf.RemoteCreateTopicRequest)
      org.ostara.remote.proto.server.RemoteCreateTopicRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ostara.remote.proto.server.ServerProto.internal_static_ostara_protobuf_RemoteCreateTopicRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ostara.remote.proto.server.ServerProto.internal_static_ostara_protobuf_RemoteCreateTopicRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ostara.remote.proto.server.RemoteCreateTopicRequest.class, org.ostara.remote.proto.server.RemoteCreateTopicRequest.Builder.class);
    }

    // Construct using org.ostara.remote.proto.server.RemoteCreateTopicRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      topic_ = "";

      cluster_ = "";

      if (partitionsBuilder_ == null) {
        partitions_ = java.util.Collections.emptyList();
      } else {
        partitions_ = null;
        partitionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.ostara.remote.proto.server.ServerProto.internal_static_ostara_protobuf_RemoteCreateTopicRequest_descriptor;
    }

    @java.lang.Override
    public org.ostara.remote.proto.server.RemoteCreateTopicRequest getDefaultInstanceForType() {
      return org.ostara.remote.proto.server.RemoteCreateTopicRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.ostara.remote.proto.server.RemoteCreateTopicRequest build() {
      org.ostara.remote.proto.server.RemoteCreateTopicRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.ostara.remote.proto.server.RemoteCreateTopicRequest buildPartial() {
      org.ostara.remote.proto.server.RemoteCreateTopicRequest result = new org.ostara.remote.proto.server.RemoteCreateTopicRequest(this);
      int from_bitField0_ = bitField0_;
      result.topic_ = topic_;
      result.cluster_ = cluster_;
      if (partitionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          partitions_ = java.util.Collections.unmodifiableList(partitions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.partitions_ = partitions_;
      } else {
        result.partitions_ = partitionsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.ostara.remote.proto.server.RemoteCreateTopicRequest) {
        return mergeFrom((org.ostara.remote.proto.server.RemoteCreateTopicRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.ostara.remote.proto.server.RemoteCreateTopicRequest other) {
      if (other == org.ostara.remote.proto.server.RemoteCreateTopicRequest.getDefaultInstance()) return this;
      if (!other.getTopic().isEmpty()) {
        topic_ = other.topic_;
        onChanged();
      }
      if (!other.getCluster().isEmpty()) {
        cluster_ = other.cluster_;
        onChanged();
      }
      if (partitionsBuilder_ == null) {
        if (!other.partitions_.isEmpty()) {
          if (partitions_.isEmpty()) {
            partitions_ = other.partitions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePartitionsIsMutable();
            partitions_.addAll(other.partitions_);
          }
          onChanged();
        }
      } else {
        if (!other.partitions_.isEmpty()) {
          if (partitionsBuilder_.isEmpty()) {
            partitionsBuilder_.dispose();
            partitionsBuilder_ = null;
            partitions_ = other.partitions_;
            bitField0_ = (bitField0_ & ~0x00000001);
            partitionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPartitionsFieldBuilder() : null;
          } else {
            partitionsBuilder_.addAllMessages(other.partitions_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              topic_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              cluster_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              org.ostara.remote.proto.PartitionMetadata m =
                  input.readMessage(
                      org.ostara.remote.proto.PartitionMetadata.parser(),
                      extensionRegistry);
              if (partitionsBuilder_ == null) {
                ensurePartitionsIsMutable();
                partitions_.add(m);
              } else {
                partitionsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object topic_ = "";
    /**
     * <code>string topic = 1;</code>
     * @return The topic.
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string topic = 1;</code>
     * @return The bytes for topic.
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string topic = 1;</code>
     * @param value The topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopic(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topic_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string topic = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopic() {
      
      topic_ = getDefaultInstance().getTopic();
      onChanged();
      return this;
    }
    /**
     * <code>string topic = 1;</code>
     * @param value The bytes for topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopicBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topic_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cluster_ = "";
    /**
     * <code>string cluster = 2;</code>
     * @return The cluster.
     */
    public java.lang.String getCluster() {
      java.lang.Object ref = cluster_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cluster_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cluster = 2;</code>
     * @return The bytes for cluster.
     */
    public com.google.protobuf.ByteString
        getClusterBytes() {
      java.lang.Object ref = cluster_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cluster_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cluster = 2;</code>
     * @param value The cluster to set.
     * @return This builder for chaining.
     */
    public Builder setCluster(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cluster_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cluster = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCluster() {
      
      cluster_ = getDefaultInstance().getCluster();
      onChanged();
      return this;
    }
    /**
     * <code>string cluster = 2;</code>
     * @param value The bytes for cluster to set.
     * @return This builder for chaining.
     */
    public Builder setClusterBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cluster_ = value;
      onChanged();
      return this;
    }

    private java.util.List<org.ostara.remote.proto.PartitionMetadata> partitions_ =
      java.util.Collections.emptyList();
    private void ensurePartitionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        partitions_ = new java.util.ArrayList<org.ostara.remote.proto.PartitionMetadata>(partitions_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.ostara.remote.proto.PartitionMetadata, org.ostara.remote.proto.PartitionMetadata.Builder, org.ostara.remote.proto.PartitionMetadataOrBuilder> partitionsBuilder_;

    /**
     * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
     */
    public java.util.List<org.ostara.remote.proto.PartitionMetadata> getPartitionsList() {
      if (partitionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(partitions_);
      } else {
        return partitionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
     */
    public int getPartitionsCount() {
      if (partitionsBuilder_ == null) {
        return partitions_.size();
      } else {
        return partitionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
     */
    public org.ostara.remote.proto.PartitionMetadata getPartitions(int index) {
      if (partitionsBuilder_ == null) {
        return partitions_.get(index);
      } else {
        return partitionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
     */
    public Builder setPartitions(
        int index, org.ostara.remote.proto.PartitionMetadata value) {
      if (partitionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionsIsMutable();
        partitions_.set(index, value);
        onChanged();
      } else {
        partitionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
     */
    public Builder setPartitions(
        int index, org.ostara.remote.proto.PartitionMetadata.Builder builderForValue) {
      if (partitionsBuilder_ == null) {
        ensurePartitionsIsMutable();
        partitions_.set(index, builderForValue.build());
        onChanged();
      } else {
        partitionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
     */
    public Builder addPartitions(org.ostara.remote.proto.PartitionMetadata value) {
      if (partitionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionsIsMutable();
        partitions_.add(value);
        onChanged();
      } else {
        partitionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
     */
    public Builder addPartitions(
        int index, org.ostara.remote.proto.PartitionMetadata value) {
      if (partitionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionsIsMutable();
        partitions_.add(index, value);
        onChanged();
      } else {
        partitionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
     */
    public Builder addPartitions(
        org.ostara.remote.proto.PartitionMetadata.Builder builderForValue) {
      if (partitionsBuilder_ == null) {
        ensurePartitionsIsMutable();
        partitions_.add(builderForValue.build());
        onChanged();
      } else {
        partitionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
     */
    public Builder addPartitions(
        int index, org.ostara.remote.proto.PartitionMetadata.Builder builderForValue) {
      if (partitionsBuilder_ == null) {
        ensurePartitionsIsMutable();
        partitions_.add(index, builderForValue.build());
        onChanged();
      } else {
        partitionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
     */
    public Builder addAllPartitions(
        java.lang.Iterable<? extends org.ostara.remote.proto.PartitionMetadata> values) {
      if (partitionsBuilder_ == null) {
        ensurePartitionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, partitions_);
        onChanged();
      } else {
        partitionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
     */
    public Builder clearPartitions() {
      if (partitionsBuilder_ == null) {
        partitions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        partitionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
     */
    public Builder removePartitions(int index) {
      if (partitionsBuilder_ == null) {
        ensurePartitionsIsMutable();
        partitions_.remove(index);
        onChanged();
      } else {
        partitionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
     */
    public org.ostara.remote.proto.PartitionMetadata.Builder getPartitionsBuilder(
        int index) {
      return getPartitionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
     */
    public org.ostara.remote.proto.PartitionMetadataOrBuilder getPartitionsOrBuilder(
        int index) {
      if (partitionsBuilder_ == null) {
        return partitions_.get(index);  } else {
        return partitionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
     */
    public java.util.List<? extends org.ostara.remote.proto.PartitionMetadataOrBuilder> 
         getPartitionsOrBuilderList() {
      if (partitionsBuilder_ != null) {
        return partitionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(partitions_);
      }
    }
    /**
     * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
     */
    public org.ostara.remote.proto.PartitionMetadata.Builder addPartitionsBuilder() {
      return getPartitionsFieldBuilder().addBuilder(
          org.ostara.remote.proto.PartitionMetadata.getDefaultInstance());
    }
    /**
     * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
     */
    public org.ostara.remote.proto.PartitionMetadata.Builder addPartitionsBuilder(
        int index) {
      return getPartitionsFieldBuilder().addBuilder(
          index, org.ostara.remote.proto.PartitionMetadata.getDefaultInstance());
    }
    /**
     * <code>repeated .ostara.protobuf.PartitionMetadata partitions = 3;</code>
     */
    public java.util.List<org.ostara.remote.proto.PartitionMetadata.Builder> 
         getPartitionsBuilderList() {
      return getPartitionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.ostara.remote.proto.PartitionMetadata, org.ostara.remote.proto.PartitionMetadata.Builder, org.ostara.remote.proto.PartitionMetadataOrBuilder> 
        getPartitionsFieldBuilder() {
      if (partitionsBuilder_ == null) {
        partitionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.ostara.remote.proto.PartitionMetadata, org.ostara.remote.proto.PartitionMetadata.Builder, org.ostara.remote.proto.PartitionMetadataOrBuilder>(
                partitions_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        partitions_ = null;
      }
      return partitionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ostara.protobuf.RemoteCreateTopicRequest)
  }

  // @@protoc_insertion_point(class_scope:ostara.protobuf.RemoteCreateTopicRequest)
  private static final org.ostara.remote.proto.server.RemoteCreateTopicRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.ostara.remote.proto.server.RemoteCreateTopicRequest();
  }

  public static org.ostara.remote.proto.server.RemoteCreateTopicRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RemoteCreateTopicRequest>
      PARSER = new com.google.protobuf.AbstractParser<RemoteCreateTopicRequest>() {
    @java.lang.Override
    public RemoteCreateTopicRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RemoteCreateTopicRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RemoteCreateTopicRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.ostara.remote.proto.server.RemoteCreateTopicRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

