// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ostara.proto

package org.ostara.remote.proto;

/**
 * Protobuf type {@code leopard.protobuf.NodeMetadata}
 */
public final class NodeMetadata extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:leopard.protobuf.NodeMetadata)
        NodeMetadataOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use NodeMetadata.newBuilder() to construct.
    private NodeMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private NodeMetadata() {
        cluster_ = "";
        name_ = "";
        host_ = "";
        state_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new NodeMetadata();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return MessageMetadataProto.internal_static_leopard_protobuf_NodeMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return MessageMetadataProto.internal_static_leopard_protobuf_NodeMetadata_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        NodeMetadata.class, NodeMetadata.Builder.class);
    }

    public static final int CLUSTER_FIELD_NUMBER = 1;
    private volatile java.lang.Object cluster_;

    /**
     * <code>string cluster = 1;</code>
     *
     * @return The cluster.
     */
    @java.lang.Override
    public java.lang.String getCluster() {
        java.lang.Object ref = cluster_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            cluster_ = s;
            return s;
        }
    }

    /**
     * <code>string cluster = 1;</code>
     *
     * @return The bytes for cluster.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getClusterBytes() {
        java.lang.Object ref = cluster_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            cluster_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;

    /**
     * <code>string name = 2;</code>
     *
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
        }
    }

    /**
     * <code>string name = 2;</code>
     *
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            name_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int HOST_FIELD_NUMBER = 3;
    private volatile java.lang.Object host_;

    /**
     * <code>string host = 3;</code>
     *
     * @return The host.
     */
    @java.lang.Override
    public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            host_ = s;
            return s;
        }
    }

    /**
     * <code>string host = 3;</code>
     *
     * @return The bytes for host.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            host_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int PORT_FIELD_NUMBER = 4;
    private int port_;

    /**
     * <code>int32 port = 4;</code>
     *
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
        return port_;
    }

    public static final int STATE_FIELD_NUMBER = 5;
    private volatile java.lang.Object state_;

    /**
     * <code>string state = 5;</code>
     *
     * @return The state.
     */
    @java.lang.Override
    public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            state_ = s;
            return s;
        }
    }

    /**
     * <code>string state = 5;</code>
     *
     * @return The bytes for state.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            state_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int LASTKEEPLIVETIME_FIELD_NUMBER = 6;
    private long lastKeepLiveTime_;

    /**
     * <code>int64 lastKeepLiveTime = 6;</code>
     *
     * @return The lastKeepLiveTime.
     */
    @java.lang.Override
    public long getLastKeepLiveTime() {
        return lastKeepLiveTime_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) {
            return true;
        }
        if (isInitialized == 0) {
            return false;
        }

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cluster_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cluster_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, host_);
        }
        if (port_ != 0) {
            output.writeInt32(4, port_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(state_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, state_);
        }
        if (lastKeepLiveTime_ != 0L) {
            output.writeInt64(6, lastKeepLiveTime_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) {
            return size;
        }

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cluster_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cluster_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, host_);
        }
        if (port_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(4, port_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(state_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, state_);
        }
        if (lastKeepLiveTime_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(6, lastKeepLiveTime_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof NodeMetadata)) {
            return super.equals(obj);
        }
        NodeMetadata other = (NodeMetadata) obj;

        if (!getCluster()
                .equals(other.getCluster())) {
            return false;
        }
        if (!getName()
                .equals(other.getName())) {
            return false;
        }
        if (!getHost()
                .equals(other.getHost())) {
            return false;
        }
        if (getPort()
                != other.getPort()) {
            return false;
        }
        if (!getState()
                .equals(other.getState())) {
            return false;
        }
        if (getLastKeepLiveTime()
                != other.getLastKeepLiveTime()) {
            return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) {
            return false;
        }
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CLUSTER_FIELD_NUMBER;
        hash = (53 * hash) + getCluster().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + HOST_FIELD_NUMBER;
        hash = (53 * hash) + getHost().hashCode();
        hash = (37 * hash) + PORT_FIELD_NUMBER;
        hash = (53 * hash) + getPort();
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + getState().hashCode();
        hash = (37 * hash) + LASTKEEPLIVETIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getLastKeepLiveTime());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static NodeMetadata parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static NodeMetadata parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static NodeMetadata parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static NodeMetadata parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static NodeMetadata parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static NodeMetadata parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static NodeMetadata parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static NodeMetadata parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static NodeMetadata parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static NodeMetadata parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static NodeMetadata parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static NodeMetadata parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(NodeMetadata prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code leopard.protobuf.NodeMetadata}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:leopard.protobuf.NodeMetadata)
            NodeMetadataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return MessageMetadataProto.internal_static_leopard_protobuf_NodeMetadata_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return MessageMetadataProto.internal_static_leopard_protobuf_NodeMetadata_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            NodeMetadata.class, NodeMetadata.Builder.class);
        }

        // Construct using org.leopard.remote.proto.NodeMetadata.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);

        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            cluster_ = "";

            name_ = "";

            host_ = "";

            port_ = 0;

            state_ = "";

            lastKeepLiveTime_ = 0L;

            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return MessageMetadataProto.internal_static_leopard_protobuf_NodeMetadata_descriptor;
        }

        @java.lang.Override
        public NodeMetadata getDefaultInstanceForType() {
            return NodeMetadata.getDefaultInstance();
        }

        @java.lang.Override
        public NodeMetadata build() {
            NodeMetadata result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public NodeMetadata buildPartial() {
            NodeMetadata result = new NodeMetadata(this);
            result.cluster_ = cluster_;
            result.name_ = name_;
            result.host_ = host_;
            result.port_ = port_;
            result.state_ = state_;
            result.lastKeepLiveTime_ = lastKeepLiveTime_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof NodeMetadata) {
                return mergeFrom((NodeMetadata) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(NodeMetadata other) {
            if (other == NodeMetadata.getDefaultInstance()) {
                return this;
            }
            if (!other.getCluster().isEmpty()) {
                cluster_ = other.cluster_;
                onChanged();
            }
            if (!other.getName().isEmpty()) {
                name_ = other.name_;
                onChanged();
            }
            if (!other.getHost().isEmpty()) {
                host_ = other.host_;
                onChanged();
            }
            if (other.getPort() != 0) {
                setPort(other.getPort());
            }
            if (!other.getState().isEmpty()) {
                state_ = other.state_;
                onChanged();
            }
            if (other.getLastKeepLiveTime() != 0L) {
                setLastKeepLiveTime(other.getLastKeepLiveTime());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            cluster_ = input.readStringRequireUtf8();

                            break;
                        } // case 10
                        case 18: {
                            name_ = input.readStringRequireUtf8();

                            break;
                        } // case 18
                        case 26: {
                            host_ = input.readStringRequireUtf8();

                            break;
                        } // case 26
                        case 32: {
                            port_ = input.readInt32();

                            break;
                        } // case 32
                        case 42: {
                            state_ = input.readStringRequireUtf8();

                            break;
                        } // case 42
                        case 48: {
                            lastKeepLiveTime_ = input.readInt64();

                            break;
                        } // case 48
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private java.lang.Object cluster_ = "";

        /**
         * <code>string cluster = 1;</code>
         *
         * @return The cluster.
         */
        public java.lang.String getCluster() {
            java.lang.Object ref = cluster_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                cluster_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string cluster = 1;</code>
         *
         * @return The bytes for cluster.
         */
        public com.google.protobuf.ByteString
        getClusterBytes() {
            java.lang.Object ref = cluster_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                cluster_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string cluster = 1;</code>
         *
         * @param value The cluster to set.
         * @return This builder for chaining.
         */
        public Builder setCluster(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            cluster_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string cluster = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearCluster() {

            cluster_ = getDefaultInstance().getCluster();
            onChanged();
            return this;
        }

        /**
         * <code>string cluster = 1;</code>
         *
         * @param value The bytes for cluster to set.
         * @return This builder for chaining.
         */
        public Builder setClusterBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            cluster_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object name_ = "";

        /**
         * <code>string name = 2;</code>
         *
         * @return The name.
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string name = 2;</code>
         *
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string name = 2;</code>
         *
         * @param value The name to set.
         * @return This builder for chaining.
         */
        public Builder setName(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            name_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string name = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearName() {

            name_ = getDefaultInstance().getName();
            onChanged();
            return this;
        }

        /**
         * <code>string name = 2;</code>
         *
         * @param value The bytes for name to set.
         * @return This builder for chaining.
         */
        public Builder setNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            name_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object host_ = "";

        /**
         * <code>string host = 3;</code>
         *
         * @return The host.
         */
        public java.lang.String getHost() {
            java.lang.Object ref = host_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                host_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string host = 3;</code>
         *
         * @return The bytes for host.
         */
        public com.google.protobuf.ByteString
        getHostBytes() {
            java.lang.Object ref = host_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                host_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string host = 3;</code>
         *
         * @param value The host to set.
         * @return This builder for chaining.
         */
        public Builder setHost(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            host_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string host = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearHost() {

            host_ = getDefaultInstance().getHost();
            onChanged();
            return this;
        }

        /**
         * <code>string host = 3;</code>
         *
         * @param value The bytes for host to set.
         * @return This builder for chaining.
         */
        public Builder setHostBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            host_ = value;
            onChanged();
            return this;
        }

        private int port_;

        /**
         * <code>int32 port = 4;</code>
         *
         * @return The port.
         */
        @java.lang.Override
        public int getPort() {
            return port_;
        }

        /**
         * <code>int32 port = 4;</code>
         *
         * @param value The port to set.
         * @return This builder for chaining.
         */
        public Builder setPort(int value) {

            port_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 port = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPort() {

            port_ = 0;
            onChanged();
            return this;
        }

        private java.lang.Object state_ = "";

        /**
         * <code>string state = 5;</code>
         *
         * @return The state.
         */
        public java.lang.String getState() {
            java.lang.Object ref = state_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                state_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string state = 5;</code>
         *
         * @return The bytes for state.
         */
        public com.google.protobuf.ByteString
        getStateBytes() {
            java.lang.Object ref = state_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                state_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string state = 5;</code>
         *
         * @param value The state to set.
         * @return This builder for chaining.
         */
        public Builder setState(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            state_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string state = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearState() {

            state_ = getDefaultInstance().getState();
            onChanged();
            return this;
        }

        /**
         * <code>string state = 5;</code>
         *
         * @param value The bytes for state to set.
         * @return This builder for chaining.
         */
        public Builder setStateBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            state_ = value;
            onChanged();
            return this;
        }

        private long lastKeepLiveTime_;

        /**
         * <code>int64 lastKeepLiveTime = 6;</code>
         *
         * @return The lastKeepLiveTime.
         */
        @java.lang.Override
        public long getLastKeepLiveTime() {
            return lastKeepLiveTime_;
        }

        /**
         * <code>int64 lastKeepLiveTime = 6;</code>
         *
         * @param value The lastKeepLiveTime to set.
         * @return This builder for chaining.
         */
        public Builder setLastKeepLiveTime(long value) {

            lastKeepLiveTime_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int64 lastKeepLiveTime = 6;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearLastKeepLiveTime() {

            lastKeepLiveTime_ = 0L;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:leopard.protobuf.NodeMetadata)
    }

    // @@protoc_insertion_point(class_scope:leopard.protobuf.NodeMetadata)
    private static final NodeMetadata DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new NodeMetadata();
    }

    public static NodeMetadata getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NodeMetadata>
            PARSER = new com.google.protobuf.AbstractParser<NodeMetadata>() {
        @java.lang.Override
        public NodeMetadata parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<NodeMetadata> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NodeMetadata> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public NodeMetadata getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

