// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.leopard.remote.proto.server;

public interface CreateTopicResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:leopard.protobuf.CreateTopicResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ack = 1;</code>
   * @return The ack.
   */
  int getAck();

  /**
   * <code>string topic = 2;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 2;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>int32 partitions = 3;</code>
   * @return The partitions.
   */
  int getPartitions();

  /**
   * <code>int32 latencies = 4;</code>
   * @return The latencies.
   */
  int getLatencies();
}
