// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.leopard.remote.proto.server;

public interface NodeRegistrationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:leopard.protobuf.NodeRegistrationResponse)
    com.google.protobuf.MessageOrBuilder {
}
