// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.leopard.remote.proto.server;

public interface QueryTopicInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shallow.protobuf.QueryTopicInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string topic = 1;</code>
   * @return A list containing the topic.
   */
  java.util.List<java.lang.String>
      getTopicList();
  /**
   * <code>repeated string topic = 1;</code>
   * @return The count of topic.
   */
  int getTopicCount();
  /**
   * <code>repeated string topic = 1;</code>
   * @param index The index of the element to return.
   * @return The topic at the given index.
   */
  java.lang.String getTopic(int index);
  /**
   * <code>repeated string topic = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the topic at the given index.
   */
  com.google.protobuf.ByteString
      getTopicBytes(int index);
}
