// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.shallow.remote.proto.server;

public interface QueryTopicInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shallow.protobuf.QueryTopicInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .shallow.protobuf.TopicMetadata&gt; topics = 1;</code>
   */
  int getTopicsCount();
  /**
   * <code>map&lt;string, .shallow.protobuf.TopicMetadata&gt; topics = 1;</code>
   */
  boolean containsTopics(
      java.lang.String key);
  /**
   * Use {@link #getTopicsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.shallow.remote.proto.TopicMetadata>
  getTopics();
  /**
   * <code>map&lt;string, .shallow.protobuf.TopicMetadata&gt; topics = 1;</code>
   */
  java.util.Map<java.lang.String, org.shallow.remote.proto.TopicMetadata>
  getTopicsMap();
  /**
   * <code>map&lt;string, .shallow.protobuf.TopicMetadata&gt; topics = 1;</code>
   */

  /* nullable */
org.shallow.remote.proto.TopicMetadata getTopicsOrDefault(
      java.lang.String key,
      /* nullable */
org.shallow.remote.proto.TopicMetadata defaultValue);
  /**
   * <code>map&lt;string, .shallow.protobuf.TopicMetadata&gt; topics = 1;</code>
   */

  org.shallow.remote.proto.TopicMetadata getTopicsOrThrow(
      java.lang.String key);
}
