// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.shallow.proto.server;

public interface CreateTopicRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:shallow.protobuf.CreateTopicRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string topic = 1;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 1;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>int32 partitions = 2;</code>
   * @return The partitions.
   */
  int getPartitions();

  /**
   * <code>int32 latency = 3;</code>
   * @return The latency.
   */
  int getLatency();
}
