// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.shallow.proto.server;

public final class ServerProto {
  private ServerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shallow_protobuf_CreateTopicRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shallow_protobuf_CreateTopicRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shallow_protobuf_CreateTopicResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shallow_protobuf_CreateTopicResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shallow_protobuf_DelTopicRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shallow_protobuf_DelTopicRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shallow_protobuf_DelTopicResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shallow_protobuf_DelTopicResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shallow_protobuf_RegisterNodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shallow_protobuf_RegisterNodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shallow_protobuf_RegisterNodeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shallow_protobuf_RegisterNodeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014server.proto\022\020shallow.protobuf\032\rshallo" +
      "w.proto\"H\n\022CreateTopicRequest\022\r\n\005topic\030\001" +
      " \001(\t\022\022\n\npartitions\030\002 \001(\005\022\017\n\007latency\030\003 \001(" +
      "\005\"V\n\023CreateTopicResponse\022\013\n\003ack\030\001 \001(\005\022\r\n" +
      "\005topic\030\002 \001(\t\022\022\n\npartitions\030\003 \001(\005\022\017\n\007late" +
      "ncy\030\004 \001(\005\" \n\017DelTopicRequest\022\r\n\005topic\030\001 " +
      "\001(\t\".\n\020DelTopicResponse\022\013\n\003ack\030\001 \001(\005\022\r\n\005" +
      "topic\030\002 \001(\t\"X\n\023RegisterNodeRequest\022\017\n\007cl" +
      "uster\030\001 \001(\t\0220\n\010metadata\030\002 \001(\0132\036.shallow." +
      "protobuf.NodeMetadata\"\026\n\024RegisterNodeRes" +
      "ponseB)\n\030org.shallow.proto.serverB\013Serve" +
      "rProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.shallow.proto.MessageMetadataProto.getDescriptor(),
        });
    internal_static_shallow_protobuf_CreateTopicRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_shallow_protobuf_CreateTopicRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shallow_protobuf_CreateTopicRequest_descriptor,
        new java.lang.String[] { "Topic", "Partitions", "Latency", });
    internal_static_shallow_protobuf_CreateTopicResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_shallow_protobuf_CreateTopicResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shallow_protobuf_CreateTopicResponse_descriptor,
        new java.lang.String[] { "Ack", "Topic", "Partitions", "Latency", });
    internal_static_shallow_protobuf_DelTopicRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_shallow_protobuf_DelTopicRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shallow_protobuf_DelTopicRequest_descriptor,
        new java.lang.String[] { "Topic", });
    internal_static_shallow_protobuf_DelTopicResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_shallow_protobuf_DelTopicResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shallow_protobuf_DelTopicResponse_descriptor,
        new java.lang.String[] { "Ack", "Topic", });
    internal_static_shallow_protobuf_RegisterNodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_shallow_protobuf_RegisterNodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shallow_protobuf_RegisterNodeRequest_descriptor,
        new java.lang.String[] { "Cluster", "Metadata", });
    internal_static_shallow_protobuf_RegisterNodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_shallow_protobuf_RegisterNodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shallow_protobuf_RegisterNodeResponse_descriptor,
        new java.lang.String[] { });
    org.shallow.proto.MessageMetadataProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
