// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.shallow.proto.server;

/**
 * Protobuf type {@code shallow.protobuf.SubscribeResponse}
 */
public final class SubscribeResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:shallow.protobuf.SubscribeResponse)
    SubscribeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubscribeResponse.newBuilder() to construct.
  private SubscribeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubscribeResponse() {
    queue_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SubscribeResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SubscribeResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            queue_ = s;
            break;
          }
          case 16: {

            ledger_ = input.readInt32();
            break;
          }
          case 24: {

            epoch_ = input.readInt32();
            break;
          }
          case 32: {

            index_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.shallow.proto.server.ServerProto.internal_static_shallow_protobuf_SubscribeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.shallow.proto.server.ServerProto.internal_static_shallow_protobuf_SubscribeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.shallow.proto.server.SubscribeResponse.class, org.shallow.proto.server.SubscribeResponse.Builder.class);
  }

  public static final int QUEUE_FIELD_NUMBER = 1;
  private volatile java.lang.Object queue_;
  /**
   * <code>string queue = 1;</code>
   * @return The queue.
   */
  @java.lang.Override
  public java.lang.String getQueue() {
    java.lang.Object ref = queue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      queue_ = s;
      return s;
    }
  }
  /**
   * <code>string queue = 1;</code>
   * @return The bytes for queue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQueueBytes() {
    java.lang.Object ref = queue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      queue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LEDGER_FIELD_NUMBER = 2;
  private int ledger_;
  /**
   * <code>int32 ledger = 2;</code>
   * @return The ledger.
   */
  @java.lang.Override
  public int getLedger() {
    return ledger_;
  }

  public static final int EPOCH_FIELD_NUMBER = 3;
  private int epoch_;
  /**
   * <code>int32 epoch = 3;</code>
   * @return The epoch.
   */
  @java.lang.Override
  public int getEpoch() {
    return epoch_;
  }

  public static final int INDEX_FIELD_NUMBER = 4;
  private long index_;
  /**
   * <code>int64 index = 4;</code>
   * @return The index.
   */
  @java.lang.Override
  public long getIndex() {
    return index_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(queue_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, queue_);
    }
    if (ledger_ != 0) {
      output.writeInt32(2, ledger_);
    }
    if (epoch_ != 0) {
      output.writeInt32(3, epoch_);
    }
    if (index_ != 0L) {
      output.writeInt64(4, index_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(queue_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, queue_);
    }
    if (ledger_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, ledger_);
    }
    if (epoch_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, epoch_);
    }
    if (index_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, index_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.shallow.proto.server.SubscribeResponse)) {
      return super.equals(obj);
    }
    org.shallow.proto.server.SubscribeResponse other = (org.shallow.proto.server.SubscribeResponse) obj;

    if (!getQueue()
        .equals(other.getQueue())) return false;
    if (getLedger()
        != other.getLedger()) return false;
    if (getEpoch()
        != other.getEpoch()) return false;
    if (getIndex()
        != other.getIndex()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + QUEUE_FIELD_NUMBER;
    hash = (53 * hash) + getQueue().hashCode();
    hash = (37 * hash) + LEDGER_FIELD_NUMBER;
    hash = (53 * hash) + getLedger();
    hash = (37 * hash) + EPOCH_FIELD_NUMBER;
    hash = (53 * hash) + getEpoch();
    hash = (37 * hash) + INDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIndex());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.shallow.proto.server.SubscribeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.shallow.proto.server.SubscribeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.shallow.proto.server.SubscribeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.shallow.proto.server.SubscribeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.shallow.proto.server.SubscribeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.shallow.proto.server.SubscribeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.shallow.proto.server.SubscribeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.shallow.proto.server.SubscribeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.shallow.proto.server.SubscribeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.shallow.proto.server.SubscribeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.shallow.proto.server.SubscribeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.shallow.proto.server.SubscribeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.shallow.proto.server.SubscribeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code shallow.protobuf.SubscribeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:shallow.protobuf.SubscribeResponse)
      org.shallow.proto.server.SubscribeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.shallow.proto.server.ServerProto.internal_static_shallow_protobuf_SubscribeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.shallow.proto.server.ServerProto.internal_static_shallow_protobuf_SubscribeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.shallow.proto.server.SubscribeResponse.class, org.shallow.proto.server.SubscribeResponse.Builder.class);
    }

    // Construct using org.shallow.proto.server.SubscribeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      queue_ = "";

      ledger_ = 0;

      epoch_ = 0;

      index_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.shallow.proto.server.ServerProto.internal_static_shallow_protobuf_SubscribeResponse_descriptor;
    }

    @java.lang.Override
    public org.shallow.proto.server.SubscribeResponse getDefaultInstanceForType() {
      return org.shallow.proto.server.SubscribeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.shallow.proto.server.SubscribeResponse build() {
      org.shallow.proto.server.SubscribeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.shallow.proto.server.SubscribeResponse buildPartial() {
      org.shallow.proto.server.SubscribeResponse result = new org.shallow.proto.server.SubscribeResponse(this);
      result.queue_ = queue_;
      result.ledger_ = ledger_;
      result.epoch_ = epoch_;
      result.index_ = index_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.shallow.proto.server.SubscribeResponse) {
        return mergeFrom((org.shallow.proto.server.SubscribeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.shallow.proto.server.SubscribeResponse other) {
      if (other == org.shallow.proto.server.SubscribeResponse.getDefaultInstance()) return this;
      if (!other.getQueue().isEmpty()) {
        queue_ = other.queue_;
        onChanged();
      }
      if (other.getLedger() != 0) {
        setLedger(other.getLedger());
      }
      if (other.getEpoch() != 0) {
        setEpoch(other.getEpoch());
      }
      if (other.getIndex() != 0L) {
        setIndex(other.getIndex());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.shallow.proto.server.SubscribeResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.shallow.proto.server.SubscribeResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object queue_ = "";
    /**
     * <code>string queue = 1;</code>
     * @return The queue.
     */
    public java.lang.String getQueue() {
      java.lang.Object ref = queue_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        queue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string queue = 1;</code>
     * @return The bytes for queue.
     */
    public com.google.protobuf.ByteString
        getQueueBytes() {
      java.lang.Object ref = queue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        queue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string queue = 1;</code>
     * @param value The queue to set.
     * @return This builder for chaining.
     */
    public Builder setQueue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      queue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string queue = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearQueue() {
      
      queue_ = getDefaultInstance().getQueue();
      onChanged();
      return this;
    }
    /**
     * <code>string queue = 1;</code>
     * @param value The bytes for queue to set.
     * @return This builder for chaining.
     */
    public Builder setQueueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      queue_ = value;
      onChanged();
      return this;
    }

    private int ledger_ ;
    /**
     * <code>int32 ledger = 2;</code>
     * @return The ledger.
     */
    @java.lang.Override
    public int getLedger() {
      return ledger_;
    }
    /**
     * <code>int32 ledger = 2;</code>
     * @param value The ledger to set.
     * @return This builder for chaining.
     */
    public Builder setLedger(int value) {
      
      ledger_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ledger = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLedger() {
      
      ledger_ = 0;
      onChanged();
      return this;
    }

    private int epoch_ ;
    /**
     * <code>int32 epoch = 3;</code>
     * @return The epoch.
     */
    @java.lang.Override
    public int getEpoch() {
      return epoch_;
    }
    /**
     * <code>int32 epoch = 3;</code>
     * @param value The epoch to set.
     * @return This builder for chaining.
     */
    public Builder setEpoch(int value) {
      
      epoch_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 epoch = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEpoch() {
      
      epoch_ = 0;
      onChanged();
      return this;
    }

    private long index_ ;
    /**
     * <code>int64 index = 4;</code>
     * @return The index.
     */
    @java.lang.Override
    public long getIndex() {
      return index_;
    }
    /**
     * <code>int64 index = 4;</code>
     * @param value The index to set.
     * @return This builder for chaining.
     */
    public Builder setIndex(long value) {
      
      index_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 index = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIndex() {
      
      index_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:shallow.protobuf.SubscribeResponse)
  }

  // @@protoc_insertion_point(class_scope:shallow.protobuf.SubscribeResponse)
  private static final org.shallow.proto.server.SubscribeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.shallow.proto.server.SubscribeResponse();
  }

  public static org.shallow.proto.server.SubscribeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubscribeResponse>
      PARSER = new com.google.protobuf.AbstractParser<SubscribeResponse>() {
    @java.lang.Override
    public SubscribeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SubscribeResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SubscribeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubscribeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.shallow.proto.server.SubscribeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

